# Generated by Django 3.0.8 on 2020-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title of entire quiz')),
                ('author', models.TextField(verbose_name='Login of an author')),
                ('question_quantity', models.IntegerField(verbose_name='Amount of available questions')),
                ('category', models.TextField(verbose_name='Category of this quiz')),
                ('total', models.IntegerField(verbose_name='Total amount of user passes through this quiz')),
            ],
        ),
    ]
