# Generated by Django 3.0.8 on 2020-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total amount of user passes through this quiz'),
        ),
    ]
