# Generated by Django 3.0.8 on 2020-08-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.IntegerField(default=0, verbose_name='Amount of right answers'),
        ),
    ]
