# Generated by Django 3.0.8 on 2020-08-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20200816_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='quiz_amount',
            field=models.IntegerField(default='test', max_length=100, verbose_name='Amount of questions of passed quiz'),
        ),
        migrations.AddField(
            model_name='result',
            name='quiz_category',
            field=models.CharField(default='test', max_length=100, verbose_name='Category of passed quiz'),
        ),
        migrations.AddField(
            model_name='result',
            name='quiz_name',
            field=models.CharField(default='test', max_length=100, verbose_name='Name of passed quiz'),
        ),
    ]
