# Generated by Django 3.0.8 on 2020-08-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20200816_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='quiz_amount',
            field=models.IntegerField(default=0, max_length=100, verbose_name='Amount of questions of passed quiz'),
        ),
    ]
